name: mlflow-env3
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.9  ## specify desired version
  - pip
  - tensorflow-deps

  ## uncomment for use with Jupyter
  ## - ipykernel

  ## PyPI packages
  - pip:
    - tensorflow-macos==2.9
    - tensorflow-metal==0.5.0  ## optional, but recommended
    - opencv-python
    - numpy
    - pandas
    - mlflow
    - boto3